#!/bin/sh

CONFIG_FILE=${CONFIG_FILE:-"/config/config.toml"}
CONFIG_DEFAULT_FILE="/config/config.toml.default"
PERL_CMD="perl -p -i -e"

INFLUXDB_BIND_ADDRESS=${INFLUXDB_BIND_ADDRESS:-"0.0.0.0"}
INFLUXDB_REPORTING_DISABLED=${INFLUXDB_REPORTING_DISABLED:-"false"}
INFLUXDB_LOGGING_LEVEL=${INFLUXDB_LOGGING_LEVEL:-"warn"}
INFLUXDB_LOGGING_FILE=${INFLUXDB_LOGGING_FILE:-"syslog"}
INFLUXDB_ADMIN_PORT=${INFLUXDB_ADMIN_PORT:-8083}
INFLUXDB_API_PORT=${INFLUXDB_API_PORT:-8086}
INFLUXDB_READ_TIMEOUT=${INFLUXDB_READ_TIMEOUT:-"5s"}
INFLUXDB_GRAPHITE_ENABLED=${INFLUXDB_GRAPHITE_ENABLED:-"false"}
INFLUXDB_GRAPHITE_ADDRESS=${INFLUXDB_GRAPHITE_ADDRESS:-"0.0.0.0"}
INFLUXDB_GRAPHITE_PORT=${INFLUXDB_GRAPHITE_PORT:-"2003"}
INFLUXDB_GRAPHITE_DATABASE=${INFLUXDB_GRAPHITE_DATABASE:-""}
INFLUXDB_GRAPHITE_UDP_ENABLED=${INFLUXDB_GRAPHITE_UDP_ENABLED:-"true"}
INFLUXDB_COLLECTD_ENABLED=${INFLUXDB_COLLECTD_ENABLED:-"false"}
INFLUXDB_COLLECTD_ADDRESS=${INFLUXDB_COLLECTD_ADDRESS:-"0.0.0.0"}
INFLUXDB_COLLECTD_PORT=${INFLUXDB_COLLECTD_PORT:-"25826"}
INFLUXDB_COLLECTD_DATABASE=${INFLUXDB_COLLECTD_DATABASE:-""}
INFLUXDB_COLLECTD_TYPESDB=${INFLUXDB_COLLECTD_TYPESDB:-"\/config\/types.db"}
INFLUXDB_UDP_ENABLED=${INFLUXDB_UDP_ENABLED:-"false"}
INFLUXDB_UDP_PORT=${INFLUXDB_UDP_PORT:-"4444"}
INFLUXDB_UDP_DATABASE=${INFLUXDB_UDP_DATABASE:-""}
INFLUXDB_UDP_SERVERS_ENABLED=${INFLUXDB_UDP_SERVERS_ENABLED:-"false"}
INFLUXDB_UDP_SERVERS_PORT=${INFLUXDB_UDP_SERVERS_PORT:-"5551"}
INFLUXDB_UDP_SERVERS_DATABASE=${INFLUXDB_UDP_SERVERS_DATABASE:-"db1"}
INFLUXDB_RAFT_PORT=${INFLUXDB_RAFT_PORT:-"8090"}
INFLUXDB_RAFT_DIR=${INFLUXDB_RAFT_DIR:-"\/data\/raft"}
INFLUXDB_RAFT_DEBUG=${INFLUXDB_RAFT_DEBUG:-"false"}
INFLUXDB_ELECTION_TIMEOUT=${INFLUXDB_ELECTION_TIMEOUT:-"1s"}
INFLUXDB_STORAGE_DIR=${INFLUXDB_STORAGE_DIR:-"\/data\/db"}
INFLUXDB_STORAGE_WRITE_BUFFER_SIZE=${INFLUXDB_STORAGE_WRITE_BUFFER_SIZE:-"10000"}
INFLUXDB_STORAGE_MAX_OPEN_SHARDS=${INFLUXDB_STORAGE_MAX_OPEN_SHARDS:-"0"}
INFLUXDB_STORAGE_POINT_BATCH_SIZE=${INFLUXDB_STORAGE_POINT_BATCH_SIZE:-"100"}
INFLUXDB_STORAGE_WRITE_BATCH_SIZE=${INFLUXDB_STORAGE_WRITE_BATCH_SIZE:-"5000000"}
INFLUXDB_STORAGE_RETENTION_SWEEP_PERIOD=${INFLUXDB_STORAGE_RETENTION_SWEEP_PERIOD:-"10m"}
INFLUXDB_CLUSTER_SEED_SERVERS=${INFLUXDB_CLUSTER_SEED_SERVERS:-"[]"}
INFLUXDB_CLUSTER_PROTOBUF_PORT=${INFLUXDB_CLUSTER_PROTOBUF_PORT:-"8099"}
INFLUXDB_CLUSTER_PROTOBUF_TIMEOUT=${INFLUXDB_CLUSTER_PROTOBUF_TIMEOUT:-"2s"}
INFLUXDB_CLUSTER_PROTOBUF_HEARTBEAT=${INFLUXDB_CLUSTER_PROTOBUF_HEARTBEAT:-"200ms"}
INFLUXDB_CLUSTER_PROTOBUF_MIN_BACKOFF=${INFLUXDB_CLUSTER_PROTOBUF_MIN_BACKOFF:-"1s"}
INFLUXDB_CLUSTER_PROTOBUF_MAX_BACKOFF=${INFLUXDB_CLUSTER_PROTOBUF_MAX_BACKOFF:-"10s"}
INFLUXDB_CLUSTER_WRITE_BUFFER_SIZE=${INFLUXDB_CLUSTER_WRITE_BUFFER_SIZE:-"1000"}
INFLUXDB_CLUSTER_MAX_RESPONSE_BUFFER_SIZE=${INFLUXDB_CLUSTER_MAX_RESPONSE_BUFFER_SIZE:-"100"}
INFLUXDB_CLUSTER_CONCURRENT_SHARD_QUERY_LIMIT=${INFLUXDB_CLUSTER_CONCURRENT_SHARD_QUERY_LIMIT:-"10"}
INFLUXDB_WAL_DIR=${INFLUXDB_WAL_DIR:-"\/data\/wal"}
INFLUXDB_WAL_FLUSH_AFTER=${INFLUXDB_WAL_FLUSH_AFTER:-"1000"}
INFLUXDB_WAL_BOOKMARK_AFTER=${INFLUXDB_WAL_BOOKMARK_AFTER:-"1000"}
INFLUXDB_WAL_INDEX_AFTER=${INFLUXDB_WAL_INDEX_AFTER:-"1000"}
INFLUXDB_WAL_REQUESTS_PER_LOGFILE=${INFLUXDB_WAL_REQUESTS_PER_LOGFILE:-"10000"}

cp -f /config/config.toml.default ${CONFIG_FILE}

${PERL_CMD} "s/%INFLUXDB_BIND_ADDRESS%/${INFLUXDB_BIND_ADDRESS}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_REPORTING_DISABLED%/${INFLUXDB_REPORTING_DISABLED}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_LOGGING_LEVEL%/${INFLUXDB_LOGGING_LEVEL}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_LOGGING_FILE%/${INFLUXDB_LOGGING_FILE}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_ADMIN_PORT%/${INFLUXDB_ADMIN_PORT}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_API_PORT%/${INFLUXDB_API_PORT}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_READ_TIMEOUT%/${INFLUXDB_READ_TIMEOUT}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_GRAPHITE_ENABLED%/${INFLUXDB_GRAPHITE_ENABLED}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_GRAPHITE_ADDRESS%/${INFLUXDB_GRAPHITE_ADDRESS}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_GRAPHITE_PORT%/${INFLUXDB_GRAPHITE_PORT}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_GRAPHITE_DATABASE%/${INFLUXDB_GRAPHITE_DATABASE}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_GRAPHITE_UDP_ENABLED%/${INFLUXDB_GRAPHITE_UDP_ENABLED}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_COLLECTD_ENABLED%/${INFLUXDB_COLLECTD_ENABLED}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_COLLECTD_ADDRESS%/${INFLUXDB_COLLECTD_ADDRESS}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_COLLECTD_DATABASE%/${INFLUXDB_COLLECTD_DATABASE}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_COLLECTD_PORT%/${INFLUXDB_COLLECTD_PORT}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_COLLECTD_TYPESDB%/${INFLUXDB_COLLECTD_TYPESDB}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_UDP_ENABLED%/${INFLUXDB_UDP_ENABLED}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_UDP_PORT%/${INFLUXDB_UDP_PORT}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_UDP_DATABASE%/${INFLUXDB_UDP_DATABASE}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_UDP_SERVERS_ENABLED%/${INFLUXDB_UDP_SERVERS_ENABLED}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_UDP_SERVERS_PORT%/${INFLUXDB_UDP_SERVERS_PORT}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_UDP_SERVERS_PORT%/${INFLUXDB_UDP_SERVERS_PORT}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_UDP_SERVERS_DATABASE%/${INFLUXDB_UDP_SERVERS_DATABASE}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_RAFT_PORT%/${INFLUXDB_RAFT_PORT}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_RAFT_DIR%/${INFLUXDB_RAFT_DIR}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_RAFT_DEBUG%/${INFLUXDB_RAFT_DEBUG}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_ELECTION_TIMEOUT%/${INFLUXDB_ELECTION_TIMEOUT}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_STORAGE_DIR%/${INFLUXDB_STORAGE_DIR}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_STORAGE_WRITE_BUFFER_SIZE%/${INFLUXDB_STORAGE_WRITE_BUFFER_SIZE}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_STORAGE_MAX_OPEN_SHARDS%/${INFLUXDB_STORAGE_MAX_OPEN_SHARDS}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_STORAGE_POINT_BATCH_SIZE%/${INFLUXDB_STORAGE_POINT_BATCH_SIZE}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_STORAGE_WRITE_BATCH_SIZE%/${INFLUXDB_STORAGE_WRITE_BATCH_SIZE}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_STORAGE_RETENTION_SWEEP_PERIOD%/${INFLUXDB_STORAGE_RETENTION_SWEEP_PERIOD}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_CLUSTER_SEED_SERVERS%/${INFLUXDB_CLUSTER_SEED_SERVERS}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_CLUSTER_PROTOBUF_PORT%/${INFLUXDB_CLUSTER_PROTOBUF_PORT}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_CLUSTER_PROTOBUF_TIMEOUT%/${INFLUXDB_CLUSTER_PROTOBUF_TIMEOUT}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_CLUSTER_PROTOBUF_HEARTBEAT%/${INFLUXDB_CLUSTER_PROTOBUF_HEARTBEAT}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_CLUSTER_PROTOBUF_MIN_BACKOFF%/${INFLUXDB_CLUSTER_PROTOBUF_MIN_BACKOFF}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_CLUSTER_PROTOBUF_MAX_BACKOFF%/${INFLUXDB_CLUSTER_PROTOBUF_MAX_BACKOFF}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_CLUSTER_WRITE_BUFFER_SIZE%/${INFLUXDB_CLUSTER_WRITE_BUFFER_SIZE}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_CLUSTER_MAX_RESPONSE_BUFFER_SIZE%/${INFLUXDB_CLUSTER_MAX_RESPONSE_BUFFER_SIZE}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_CLUSTER_CONCURRENT_SHARD_QUERY_LIMIT%/${INFLUXDB_CLUSTER_CONCURRENT_SHARD_QUERY_LIMIT}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_WAL_DIR%/${INFLUXDB_WAL_DIR}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_WAL_FLUSH_AFTER%/${INFLUXDB_WAL_FLUSH_AFTER}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_WAL_BOOKMARK_AFTER%/${INFLUXDB_WAL_BOOKMARK_AFTER}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_WAL_INDEX_AFTER%/${INFLUXDB_WAL_INDEX_AFTER}/g" ${CONFIG_FILE}
${PERL_CMD} "s/%INFLUXDB_WAL_REQUESTS_PER_LOGFILE%/${INFLUXDB_WAL_REQUESTS_PER_LOGFILE}/g" ${CONFIG_FILE}

/usr/bin/influxdb -config ${CONFIG_FILE}
